#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Write a placeholder model header with zero weights.

The loader compiles a model in unconditionally, and collecting the features a
real model is trained from requires the loader. This breaks that loop: build
against this header, run the profiler in `collect` mode, train, then rebuild
against the trained header. Every page scores the same under these weights, so
it is of no use for a measurement.
"""
import os
import sys

# Must match src/common_kern.h.
L0_IN, L0_OUT, L1_OUT = 32, 192, 96


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "models", "mlp_q8_bootstrap.h")
    os.makedirs(os.path.dirname(out), exist_ok=True)

    zeros = lambda n: ", ".join(["0"] * n)
    ones = lambda n: ", ".join(["1.0000000000"] * n)

    with open(out, "w") as f:
        f.write("/* SPDX-License-Identifier: GPL-2.0 */\n")
        f.write("/*\n")
        f.write(" * Generated by ml/bootstrap_model.py -- do not edit.\n")
        f.write(" *\n")
        f.write(" * Placeholder weights, all zero. Lets the loader build so that\n")
        f.write(" * `collect` mode can produce training features. Replace with the\n")
        f.write(" * output of ml/train_and_export.py before measuring anything.\n")
        f.write(" */\n")
        f.write("#ifndef MLP_Q8_H\n#define MLP_Q8_H\n\n")
        f.write('#include "common_kern.h"\n\n')
        f.write("static const __s32 L0_IN_ZP[] = { 0 };\n")
        f.write("static const __u32 L0_OUT_ZP[] = { 0 };\n")
        f.write("static const __u32 L1_OUT_ZP[] = { 0 };\n")
        f.write("static const __u32 L2_OUT_ZP[] = { 0 };\n")
        f.write("static const __s32 CLS_THR_QINT8[] = { 128 };\n\n")
        for name in ("L0_IN", "L0_OUT", "L1_IN", "L1_OUT", "L2_IN", "L2_OUT"):
            f.write(f"static const float {name}_SCALE[] = {{ 1.0000000000 }};\n")
        f.write("\n")
        f.write(f"static const __s8 L0_W[] = {{ {zeros(L0_OUT * L0_IN)} }};\n")
        f.write(f"static const __s32 L0_B_INT32[] = {{ {zeros(L0_OUT)} }};\n")
        f.write(f"static const float L0_W_SCALE[] = {{ {ones(L0_OUT)} }};\n\n")
        f.write(f"static const __s8 L1_W[] = {{ {zeros(L1_OUT * L0_OUT)} }};\n")
        f.write(f"static const __s32 L1_B_INT32[] = {{ {zeros(L1_OUT)} }};\n")
        f.write(f"static const float L1_W_SCALE[] = {{ {ones(L1_OUT)} }};\n\n")
        f.write(f"static const __s8 L2_W[] = {{ {zeros(L1_OUT)} }};\n")
        f.write("static const __s32 L2_B_INT32[] = { 0 };\n")
        f.write("static const float L2_W_SCALE[] = { 1.0000000000 };\n\n")
        f.write("#endif\n")

    print(f"wrote {out}")


if __name__ == "__main__":
    main()
